package br.com.cidandrade.aulas.gui;

import br.com.cidandrade.aulas.Calculadora;

public class CalculadoraGUI extends javax.swing.JFrame {

    Calculadora calculadora = new Calculadora();

    /**
     * Creates new form CalculadoraGUI
     */
    public CalculadoraGUI() {
        initComponents();

        jbDiv.setText("\u00F7");
        jbRaiz.setText("\u221A");
        jbElev.setText("\u005E");
        jbSinal.setText("\u00B1");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpPrincipal = new javax.swing.JPanel();
        jtVisor = new javax.swing.JTextField();
        jbNum7 = new javax.swing.JButton();
        jbNum9 = new javax.swing.JButton();
        jbNum8 = new javax.swing.JButton();
        jbNum6 = new javax.swing.JButton();
        jbNum4 = new javax.swing.JButton();
        jbNum5 = new javax.swing.JButton();
        jbNum1 = new javax.swing.JButton();
        jbNum2 = new javax.swing.JButton();
        jbNum3 = new javax.swing.JButton();
        jbNum0 = new javax.swing.JButton();
        jbPonto = new javax.swing.JButton();
        jbEnter = new javax.swing.JButton();
        jbLimpa = new javax.swing.JButton();
        jbRaiz = new javax.swing.JButton();
        jbElev = new javax.swing.JButton();
        jbDiv = new javax.swing.JButton();
        jbMult = new javax.swing.JButton();
        jbSubt = new javax.swing.JButton();
        jbSoma = new javax.swing.JButton();
        jbSinal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora");
        setResizable(false);

        jtVisor.setEditable(false);
        jtVisor.setFont(new java.awt.Font("Courier New", 1, 48)); // NOI18N
        jtVisor.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtVisor.setText("0.");

        jbNum7.setBackground(new java.awt.Color(0, 51, 255));
        jbNum7.setFont(new java.awt.Font("Liberation Sans", 1, 42)); // NOI18N
        jbNum7.setForeground(new java.awt.Color(255, 255, 255));
        jbNum7.setText("7");
        jbNum7.setMaximumSize(new java.awt.Dimension(60, 60));
        jbNum7.setMinimumSize(new java.awt.Dimension(60, 60));
        jbNum7.setPreferredSize(new java.awt.Dimension(60, 60));
        jbNum7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNum7ActionPerformed(evt);
            }
        });

        jbNum9.setBackground(new java.awt.Color(0, 51, 255));
        jbNum9.setFont(new java.awt.Font("Liberation Sans", 1, 42)); // NOI18N
        jbNum9.setForeground(new java.awt.Color(255, 255, 255));
        jbNum9.setText("9");
        jbNum9.setMaximumSize(new java.awt.Dimension(60, 60));
        jbNum9.setMinimumSize(new java.awt.Dimension(60, 60));
        jbNum9.setPreferredSize(new java.awt.Dimension(60, 60));
        jbNum9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNum9ActionPerformed(evt);
            }
        });

        jbNum8.setBackground(new java.awt.Color(0, 51, 255));
        jbNum8.setFont(new java.awt.Font("Liberation Sans", 1, 42)); // NOI18N
        jbNum8.setForeground(new java.awt.Color(255, 255, 255));
        jbNum8.setText("8");
        jbNum8.setMaximumSize(new java.awt.Dimension(60, 60));
        jbNum8.setMinimumSize(new java.awt.Dimension(60, 60));
        jbNum8.setPreferredSize(new java.awt.Dimension(60, 60));
        jbNum8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNum8ActionPerformed(evt);
            }
        });

        jbNum6.setBackground(new java.awt.Color(0, 51, 255));
        jbNum6.setFont(new java.awt.Font("Liberation Sans", 1, 42)); // NOI18N
        jbNum6.setForeground(new java.awt.Color(255, 255, 255));
        jbNum6.setText("6");
        jbNum6.setMaximumSize(new java.awt.Dimension(60, 60));
        jbNum6.setMinimumSize(new java.awt.Dimension(60, 60));
        jbNum6.setPreferredSize(new java.awt.Dimension(60, 60));
        jbNum6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNum6ActionPerformed(evt);
            }
        });

        jbNum4.setBackground(new java.awt.Color(0, 51, 255));
        jbNum4.setFont(new java.awt.Font("Liberation Sans", 1, 42)); // NOI18N
        jbNum4.setForeground(new java.awt.Color(255, 255, 255));
        jbNum4.setText("4");
        jbNum4.setMaximumSize(new java.awt.Dimension(60, 60));
        jbNum4.setMinimumSize(new java.awt.Dimension(60, 60));
        jbNum4.setPreferredSize(new java.awt.Dimension(60, 60));
        jbNum4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNum4ActionPerformed(evt);
            }
        });

        jbNum5.setBackground(new java.awt.Color(0, 51, 255));
        jbNum5.setFont(new java.awt.Font("Liberation Sans", 1, 42)); // NOI18N
        jbNum5.setForeground(new java.awt.Color(255, 255, 255));
        jbNum5.setText("5");
        jbNum5.setMaximumSize(new java.awt.Dimension(60, 60));
        jbNum5.setMinimumSize(new java.awt.Dimension(60, 60));
        jbNum5.setPreferredSize(new java.awt.Dimension(60, 60));
        jbNum5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNum5ActionPerformed(evt);
            }
        });

        jbNum1.setBackground(new java.awt.Color(0, 51, 255));
        jbNum1.setFont(new java.awt.Font("Liberation Sans", 1, 42)); // NOI18N
        jbNum1.setForeground(new java.awt.Color(255, 255, 255));
        jbNum1.setText("1");
        jbNum1.setMaximumSize(new java.awt.Dimension(60, 60));
        jbNum1.setMinimumSize(new java.awt.Dimension(60, 60));
        jbNum1.setPreferredSize(new java.awt.Dimension(60, 60));
        jbNum1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNum1ActionPerformed(evt);
            }
        });

        jbNum2.setBackground(new java.awt.Color(0, 51, 255));
        jbNum2.setFont(new java.awt.Font("Liberation Sans", 1, 42)); // NOI18N
        jbNum2.setForeground(new java.awt.Color(255, 255, 255));
        jbNum2.setText("2");
        jbNum2.setMaximumSize(new java.awt.Dimension(60, 60));
        jbNum2.setMinimumSize(new java.awt.Dimension(60, 60));
        jbNum2.setPreferredSize(new java.awt.Dimension(60, 60));
        jbNum2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNum2ActionPerformed(evt);
            }
        });

        jbNum3.setBackground(new java.awt.Color(0, 51, 255));
        jbNum3.setFont(new java.awt.Font("Liberation Sans", 1, 42)); // NOI18N
        jbNum3.setForeground(new java.awt.Color(255, 255, 255));
        jbNum3.setText("3");
        jbNum3.setMaximumSize(new java.awt.Dimension(60, 60));
        jbNum3.setMinimumSize(new java.awt.Dimension(60, 60));
        jbNum3.setPreferredSize(new java.awt.Dimension(60, 60));
        jbNum3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNum3ActionPerformed(evt);
            }
        });

        jbNum0.setBackground(new java.awt.Color(0, 51, 255));
        jbNum0.setFont(new java.awt.Font("Liberation Sans", 1, 42)); // NOI18N
        jbNum0.setForeground(new java.awt.Color(255, 255, 255));
        jbNum0.setText("0");
        jbNum0.setMaximumSize(new java.awt.Dimension(60, 60));
        jbNum0.setMinimumSize(new java.awt.Dimension(60, 60));
        jbNum0.setPreferredSize(new java.awt.Dimension(60, 60));
        jbNum0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNum0ActionPerformed(evt);
            }
        });

        jbPonto.setBackground(new java.awt.Color(0, 51, 255));
        jbPonto.setFont(new java.awt.Font("Liberation Sans", 1, 42)); // NOI18N
        jbPonto.setForeground(new java.awt.Color(255, 255, 255));
        jbPonto.setText(".");
        jbPonto.setMaximumSize(new java.awt.Dimension(60, 60));
        jbPonto.setMinimumSize(new java.awt.Dimension(60, 60));
        jbPonto.setPreferredSize(new java.awt.Dimension(60, 60));
        jbPonto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPontoActionPerformed(evt);
            }
        });

        jbEnter.setBackground(new java.awt.Color(0, 51, 255));
        jbEnter.setFont(new java.awt.Font("Liberation Sans", 1, 12)); // NOI18N
        jbEnter.setForeground(new java.awt.Color(255, 255, 255));
        jbEnter.setText("ENTER");
        jbEnter.setMaximumSize(new java.awt.Dimension(60, 60));
        jbEnter.setMinimumSize(new java.awt.Dimension(60, 60));
        jbEnter.setPreferredSize(new java.awt.Dimension(60, 60));
        jbEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEnterActionPerformed(evt);
            }
        });

        jbLimpa.setBackground(new java.awt.Color(0, 51, 255));
        jbLimpa.setFont(new java.awt.Font("Liberation Sans", 1, 42)); // NOI18N
        jbLimpa.setForeground(new java.awt.Color(255, 255, 255));
        jbLimpa.setText("C");
        jbLimpa.setMaximumSize(new java.awt.Dimension(60, 60));
        jbLimpa.setMinimumSize(new java.awt.Dimension(60, 60));
        jbLimpa.setPreferredSize(new java.awt.Dimension(60, 60));
        jbLimpa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimpaActionPerformed(evt);
            }
        });

        jbRaiz.setBackground(new java.awt.Color(0, 51, 255));
        jbRaiz.setFont(new java.awt.Font("Liberation Sans", 1, 42)); // NOI18N
        jbRaiz.setForeground(new java.awt.Color(255, 255, 255));
        jbRaiz.setText("R");
        jbRaiz.setMaximumSize(new java.awt.Dimension(60, 60));
        jbRaiz.setMinimumSize(new java.awt.Dimension(60, 60));
        jbRaiz.setPreferredSize(new java.awt.Dimension(60, 60));
        jbRaiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbRaizActionPerformed(evt);
            }
        });

        jbElev.setBackground(new java.awt.Color(0, 51, 255));
        jbElev.setFont(new java.awt.Font("Liberation Sans", 1, 42)); // NOI18N
        jbElev.setForeground(new java.awt.Color(255, 255, 255));
        jbElev.setText("E");
        jbElev.setMaximumSize(new java.awt.Dimension(60, 60));
        jbElev.setMinimumSize(new java.awt.Dimension(60, 60));
        jbElev.setPreferredSize(new java.awt.Dimension(60, 60));
        jbElev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbElevActionPerformed(evt);
            }
        });

        jbDiv.setBackground(new java.awt.Color(0, 51, 255));
        jbDiv.setFont(new java.awt.Font("Liberation Sans", 1, 42)); // NOI18N
        jbDiv.setForeground(new java.awt.Color(255, 255, 255));
        jbDiv.setText("/");
        jbDiv.setMaximumSize(new java.awt.Dimension(60, 60));
        jbDiv.setMinimumSize(new java.awt.Dimension(60, 60));
        jbDiv.setPreferredSize(new java.awt.Dimension(60, 60));
        jbDiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDivActionPerformed(evt);
            }
        });

        jbMult.setBackground(new java.awt.Color(0, 51, 255));
        jbMult.setFont(new java.awt.Font("Liberation Sans", 1, 42)); // NOI18N
        jbMult.setForeground(new java.awt.Color(255, 255, 255));
        jbMult.setText("x");
        jbMult.setMaximumSize(new java.awt.Dimension(60, 60));
        jbMult.setMinimumSize(new java.awt.Dimension(60, 60));
        jbMult.setPreferredSize(new java.awt.Dimension(60, 60));
        jbMult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbMultActionPerformed(evt);
            }
        });

        jbSubt.setBackground(new java.awt.Color(0, 51, 255));
        jbSubt.setFont(new java.awt.Font("Liberation Sans", 1, 42)); // NOI18N
        jbSubt.setForeground(new java.awt.Color(255, 255, 255));
        jbSubt.setText("-");
        jbSubt.setMaximumSize(new java.awt.Dimension(60, 60));
        jbSubt.setMinimumSize(new java.awt.Dimension(60, 60));
        jbSubt.setPreferredSize(new java.awt.Dimension(60, 60));
        jbSubt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSubtActionPerformed(evt);
            }
        });

        jbSoma.setBackground(new java.awt.Color(0, 51, 255));
        jbSoma.setFont(new java.awt.Font("Liberation Sans", 1, 42)); // NOI18N
        jbSoma.setForeground(new java.awt.Color(255, 255, 255));
        jbSoma.setText("+");
        jbSoma.setMaximumSize(new java.awt.Dimension(60, 60));
        jbSoma.setMinimumSize(new java.awt.Dimension(60, 60));
        jbSoma.setPreferredSize(new java.awt.Dimension(60, 60));
        jbSoma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSomaActionPerformed(evt);
            }
        });

        jbSinal.setBackground(new java.awt.Color(0, 51, 255));
        jbSinal.setFont(new java.awt.Font("Liberation Sans", 1, 42)); // NOI18N
        jbSinal.setForeground(new java.awt.Color(255, 255, 255));
        jbSinal.setText("+-");
        jbSinal.setMaximumSize(new java.awt.Dimension(60, 60));
        jbSinal.setMinimumSize(new java.awt.Dimension(60, 60));
        jbSinal.setPreferredSize(new java.awt.Dimension(60, 60));
        jbSinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSinalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpPrincipalLayout = new javax.swing.GroupLayout(jpPrincipal);
        jpPrincipal.setLayout(jpPrincipalLayout);
        jpPrincipalLayout.setHorizontalGroup(
            jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtVisor)
                    .addGroup(jpPrincipalLayout.createSequentialGroup()
                        .addGroup(jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpPrincipalLayout.createSequentialGroup()
                                .addComponent(jbNum7, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbNum8, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbNum9, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpPrincipalLayout.createSequentialGroup()
                                .addComponent(jbNum4, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbNum5, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbNum6, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpPrincipalLayout.createSequentialGroup()
                                .addComponent(jbNum1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbNum2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbNum3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpPrincipalLayout.createSequentialGroup()
                                .addComponent(jbNum0, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbPonto, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbSinal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jbEnter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbLimpa, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                            .addComponent(jbRaiz, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                            .addComponent(jbElev, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbDiv, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbMult, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbSubt, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbSoma, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jpPrincipalLayout.setVerticalGroup(
            jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtVisor, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpPrincipalLayout.createSequentialGroup()
                        .addComponent(jbDiv, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbMult, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbSubt, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbSoma, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpPrincipalLayout.createSequentialGroup()
                        .addGroup(jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpPrincipalLayout.createSequentialGroup()
                                .addGroup(jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jbNum7, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbNum9, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbNum8, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jbNum4, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbNum6, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbNum5, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jbNum1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbNum3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbNum2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jpPrincipalLayout.createSequentialGroup()
                                .addComponent(jbLimpa, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbRaiz, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbElev, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpPrincipalLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jbNum0, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbPonto, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbSinal, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jpPrincipalLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jbEnter, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbNum1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNum1ActionPerformed
        jtVisor.setText(calculadora.entrNumerica(1));
    }//GEN-LAST:event_jbNum1ActionPerformed

    private void jbNum0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNum0ActionPerformed
        jtVisor.setText(calculadora.entrNumerica(0));
    }//GEN-LAST:event_jbNum0ActionPerformed

    private void jbNum2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNum2ActionPerformed
        jtVisor.setText(calculadora.entrNumerica(2));
    }//GEN-LAST:event_jbNum2ActionPerformed

    private void jbNum3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNum3ActionPerformed
        jtVisor.setText(calculadora.entrNumerica(3));
    }//GEN-LAST:event_jbNum3ActionPerformed

    private void jbNum4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNum4ActionPerformed
        jtVisor.setText(calculadora.entrNumerica(4));
    }//GEN-LAST:event_jbNum4ActionPerformed

    private void jbNum5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNum5ActionPerformed
        jtVisor.setText(calculadora.entrNumerica(5));
    }//GEN-LAST:event_jbNum5ActionPerformed

    private void jbNum6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNum6ActionPerformed
        jtVisor.setText(calculadora.entrNumerica(6));
    }//GEN-LAST:event_jbNum6ActionPerformed

    private void jbNum7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNum7ActionPerformed
        jtVisor.setText(calculadora.entrNumerica(7));
    }//GEN-LAST:event_jbNum7ActionPerformed

    private void jbNum8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNum8ActionPerformed
        jtVisor.setText(calculadora.entrNumerica(8));
    }//GEN-LAST:event_jbNum8ActionPerformed

    private void jbNum9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNum9ActionPerformed
        jtVisor.setText(calculadora.entrNumerica(9));
    }//GEN-LAST:event_jbNum9ActionPerformed

    private void jbPontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPontoActionPerformed
        jtVisor.setText(calculadora.pontoPress());
    }//GEN-LAST:event_jbPontoActionPerformed

    private void jbLimpaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimpaActionPerformed
        jtVisor.setText(calculadora.limpa());
    }//GEN-LAST:event_jbLimpaActionPerformed

    private void jbRaizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbRaizActionPerformed
        jtVisor.setText(calculadora.raizPress());
    }//GEN-LAST:event_jbRaizActionPerformed

    private void jbEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEnterActionPerformed
        calculadora.enterPress();
    }//GEN-LAST:event_jbEnterActionPerformed

    private void jbSomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSomaActionPerformed
        jtVisor.setText(calculadora.somaPress());
    }//GEN-LAST:event_jbSomaActionPerformed

    private void jbMultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbMultActionPerformed
        jtVisor.setText(calculadora.multPress());
    }//GEN-LAST:event_jbMultActionPerformed

    private void jbDivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDivActionPerformed
        jtVisor.setText(calculadora.divPress());
    }//GEN-LAST:event_jbDivActionPerformed

    private void jbSubtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSubtActionPerformed
        jtVisor.setText(calculadora.subtraiPress());
    }//GEN-LAST:event_jbSubtActionPerformed

    private void jbSinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSinalActionPerformed
        jtVisor.setText(calculadora.sinalPress());
    }//GEN-LAST:event_jbSinalActionPerformed

    private void jbElevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbElevActionPerformed
        jtVisor.setText(calculadora.elevPress());
    }//GEN-LAST:event_jbElevActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculadoraGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculadoraGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculadoraGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculadoraGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculadoraGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbDiv;
    private javax.swing.JButton jbElev;
    private javax.swing.JButton jbEnter;
    private javax.swing.JButton jbLimpa;
    private javax.swing.JButton jbMult;
    private javax.swing.JButton jbNum0;
    private javax.swing.JButton jbNum1;
    private javax.swing.JButton jbNum2;
    private javax.swing.JButton jbNum3;
    private javax.swing.JButton jbNum4;
    private javax.swing.JButton jbNum5;
    private javax.swing.JButton jbNum6;
    private javax.swing.JButton jbNum7;
    private javax.swing.JButton jbNum8;
    private javax.swing.JButton jbNum9;
    private javax.swing.JButton jbPonto;
    private javax.swing.JButton jbRaiz;
    private javax.swing.JButton jbSinal;
    private javax.swing.JButton jbSoma;
    private javax.swing.JButton jbSubt;
    private javax.swing.JPanel jpPrincipal;
    private javax.swing.JTextField jtVisor;
    // End of variables declaration//GEN-END:variables
}
